services:
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - frontend_backend_net

  backend:
    build: ./backend
    networks:
      - frontend_backend_net


networks:
  frontend_backend_net:
    driver: bridge

