services:
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - frontend_backend_net

  backend:
    build: ./backend
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=${MONGO_DB}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SERPAPI_API_KEY=${SERPAPI_API_KEY}
      - secret=${secret}
    networks:
      - frontend_backend_net
    ports:
      - "5000:5000"  


networks:
  frontend_backend_net:
    driver: bridge

