# Utiliser une image Python
FROM python:3.9

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers requirements.txt et installer les dépendances
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copier le reste du code
COPY . .

# Exposer le port pour Flask
EXPOSE 5000

# Démarrer le serveur Flask
CMD ["python", "projettraveleefback/app.py"]  